#!/bin/sh

# Wait a second before booting off the "SDCard"
autoboot_timeout=1

global linux.bootargs.base="console=ttyAMA0,115200n8"

global boot.default=mmc

# set a fancy prompt (if support is compiled in)
PS1="\e[1;31m[barebox@\h]:\w\e[0m\n# "
